const puppeteer = require('puppeteer');

/**
 * Generate a PDF receipt for a customer.
 * @param {object} data - receipt data object
 * @returns {Buffer} PDF buffer
 */
async function generateReceiptPDF(data) {
  const { customer, payments, totalPaid, totalPending, adminName } = data;

  const paymentRows = payments.map((p, i) => `
    <tr>
      <td>${i + 1}</td>
      <td>${new Date(p.payment_date).toLocaleDateString('en-IN')}</td>
      <td>${p.receipt_number || '-'}</td>
      <td>${p.method || '-'}</td>
      <td style="text-align:right">₹${parseFloat(p.amount).toFixed(2)}</td>
    </tr>
  `).join('');

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8" />
      <title>Payment Receipt — Bhavesh RTO</title>
      <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: 'Arial', sans-serif; color: #222; padding: 32px; }
        .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; border-bottom: 3px solid #1e3a5f; padding-bottom: 16px; }
        .brand h1 { font-size: 22px; color: #1e3a5f; }
        .brand p { font-size: 12px; color: #666; margin-top: 4px; }
        .receipt-label { font-size: 14px; font-weight: bold; color: #1e3a5f; text-align: right; }
        .section-title { font-size: 13px; font-weight: bold; color: #1e3a5f; background: #f0f4f9; padding: 8px 12px; margin: 16px 0 8px; border-left: 4px solid #1e3a5f; }
        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px 24px; padding: 0 4px; }
        .info-grid .label { font-size: 11px; color: #888; }
        .info-grid .value { font-size: 13px; font-weight: 500; }
        table { width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 8px; }
        th { background: #1e3a5f; color: #fff; padding: 8px 10px; text-align: left; }
        td { padding: 7px 10px; border-bottom: 1px solid #eee; }
        tr:nth-child(even) td { background: #f9fafc; }
        .summary-box { margin-top: 20px; border: 1px solid #e0e7ef; border-radius: 8px; overflow: hidden; }
        .summary-row { display: flex; justify-content: space-between; padding: 10px 16px; font-size: 13px; }
        .summary-row:not(:last-child) { border-bottom: 1px solid #e0e7ef; }
        .summary-row.total { background: #1e3a5f; color: #fff; font-weight: bold; font-size: 14px; }
        .summary-row.pending { background: #fff3cd; color: #856404; font-weight: bold; }
        .footer { margin-top: 32px; text-align: center; font-size: 11px; color: #aaa; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="brand">
          <h1>Bhavesh Solanki</h1>
          <p>RTO & Insurance Advisor</p>
          <p>Generated by: ${adminName || 'Admin'}</p>
        </div>
        <div class="receipt-label">
          PAYMENT RECEIPT<br/>
          <span style="font-weight:normal; font-size:12px;">Date: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</span>
        </div>
      </div>

      <div class="section-title">Customer Details</div>
      <div class="info-grid">
        <div><div class="label">Name</div><div class="value">${customer.name}</div></div>
        <div><div class="label">Contact</div><div class="value">${customer.contact_number}</div></div>
        <div><div class="label">Category</div><div class="value">${customer.category.replace('_', '/').toUpperCase()}</div></div>
        <div><div class="label">Vehicle No.</div><div class="value">${customer.vehicle_number || '-'}</div></div>
        <div><div class="label">Start Date</div><div class="value">${customer.start_date ? new Date(customer.start_date).toLocaleDateString('en-IN') : '-'}</div></div>
        <div><div class="label">End Date</div><div class="value">${customer.end_date ? new Date(customer.end_date).toLocaleDateString('en-IN') : '-'}</div></div>
      </div>

      <div class="section-title">Payment History</div>
      ${payments.length > 0 ? `
      <table>
        <thead>
          <tr><th>#</th><th>Date</th><th>Receipt No.</th><th>Method</th><th style="text-align:right">Amount</th></tr>
        </thead>
        <tbody>${paymentRows}</tbody>
      </table>` : '<p style="padding:8px 4px; color:#888; font-size:12px;">No payments recorded yet.</p>'}

      <div class="summary-box" style="margin-top:16px;">
        <div class="summary-row">
          <span>Total Amount</span>
          <span>₹${parseFloat(customer.amount_total).toFixed(2)}</span>
        </div>
        <div class="summary-row">
          <span>Total Collected</span>
          <span style="color:#166534;">₹${parseFloat(totalPaid).toFixed(2)}</span>
        </div>
        <div class="summary-row pending">
          <span>Pending Amount</span>
          <span>₹${parseFloat(totalPending).toFixed(2)}</span>
        </div>
      </div>

      <div class="footer">
        This is a computer-generated receipt. — Bhavesh Solanki RTO & Insurance Advisor
      </div>
    </body>
    </html>
  `;

  const browser = await puppeteer.launch({
    headless: 'new',
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '20px', bottom: '20px', left: '20px', right: '20px' },
    });
    return pdfBuffer;
  } finally {
    await browser.close();
  }
}

module.exports = { generateReceiptPDF };
